### ISSUE TITLE
在linux上使用AES解密字符串报错

### ISSUE THREAD

**Issue by whhya** [vipshop/vjtools#113]
com.vip.vjtools.vjkit.base.type.UncheckedException: Given final block not properly padded
        at com.vip.vjtools.vjkit.base.ExceptionUtil.unchecked(ExceptionUtil.java:60) ~[vjkit-1.0.5.jar:?]
        at com.vip.vjtools.vjkit.security.CryptoUtil.aes(CryptoUtil.java:138) ~[vjkit-1.0.5.jar:?]
        at com.vip.vjtools.vjkit.security.CryptoUtil.aesDecrypt(CryptoUtil.java:108) ~[vjkit-1.0.5.jar:?]

**Comment by whhya** [comment]
已解决  自己加密错误了
