### ISSUE TITLE
vjtop --memory  PID 抛异常

### ISSUE THREAD

**Issue by kevinYin** [vipshop/vjtools#137]
参照文档使用vjtop，抛异常，麻烦看下是什么原因
[root@XXXX vjtop]# ./vjtop.sh --memory  22304
joptsimple.UnrecognizedOptionException: memory is not a recognized option
        at joptsimple.OptionException.unrecognizedOption(OptionException.java:108)
        at joptsimple.OptionParser.handleLongOptionToken(OptionParser.java:449)
        at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:56)
        at joptsimple.OptionParser.parse(OptionParser.java:381)
        at com.vip.vjtools.vjtop.VJTop.main(VJTop.java:37)

**Comment by yixius** [comment]
单看报错，说memory不是个选项，感觉应该是参考文档没随着代码版本更新而更新；你可以去这行代码那里看一下新的参数名称@kevinYin

**Comment by kevinYin** [comment]
> 单看报错，说memory不是个选项，感觉应该是参考文档没随着代码版本更新而更新；你可以去这行代码那里看一下新的参数名称@kevinYin

嗯 已经找到问题所在，参数不对， 应该是 ./vjtop.sh -m 5 PID
