### ISSUE TITLE
vjtop-1.0.5在 jdk1.7.0_80运行空指针异常

### ISSUE THREAD

**Issue by githubyong** [vipshop/vjtools#144]
[root@xx]# vjtop.sh 3028
/home/ftprazor/yong/vjtools/jdk1.7.0_80/bin/java

java.lang.NullPointerException
	at com.vip.vjtools.vjtop.VMInfo.updateMemoryPool(VMInfo.java:359)
	at com.vip.vjtools.vjtop.VMInfo.update(VMInfo.java:226)
	at com.vip.vjtools.vjtop.VMDetailView.printView(VMDetailView.java:64)
	at com.vip.vjtools.vjtop.VJTop.run(VJTop.java:159)
	at com.vip.vjtools.vjtop.VJTop.main(VJTop.java:141)
 PID: 3028 - 11:43:46 JVM: 1.6.0_41 USER: root UPTIME: 2d22h
 PROCESS:  0.00% cpu( 0.00% of 8 core), 346 thread
 MEMORY: 1763m rss, 1769m peak, 0m swap | DISK: 0B read, 0B write
 THREAD: 330 live, 45 daemon, 336 peak, 0 new | CLASS: 13003 loaded, 282 unloaded, 0 new
 HEAP: 192m/387m/389m eden, 34m/56m sur, 611m/1008m old
 NON-HEAP: 55m/56m/64m perm, 19m/22m/48m codeCache
java.lang.NullPointerException
	at com.vip.vjtools.vjtop.VMDetailView.printJvmInfo(VMDetailView.java:158)
	at com.vip.vjtools.vjtop.VMDetailView.printView(VMDetailView.java:71)
	at com.vip.vjtools.vjtop.VJTop.run(VJTop.java:159)
	at com.vip.vjtools.vjtop.VJTop.main(VJTop.java:141)

**Comment by githubyong** [comment]
VMinfo.java 371行报错:Cannot resolve method 'getMappedBufferPool()
`mapUsed == 0 ? 0 : jmxClient.getBufferPoolManager().getMappedBufferPool().getCount());`
com.vip.vjtools.vjtop.data.jmx.JmxBufferPoolManager没提交完整吧

**Comment by githubyong** [comment]
> VMinfo.java 371行报错:Cannot resolve method 'getMappedBufferPool()
> `mapUsed == 0 ? 0 : jmxClient.getBufferPoolManager().getMappedBufferPool().getCount());`
> com.vip.vjtools.vjtop.data.jmx.JmxBufferPoolManager没提交完整吧
com.vip.vjtools.vjtop.data.jmx.JmxBufferPoolManager增加mappedBufferPool的getter方法后编译出1.0.8-SNAPSHOT运行ok

**Comment by calvin1978** [comment]
fixed
