### ISSUE TITLE
vjtop <PID> 异常，PID是主机上看到的Docker中的进程

### ISSUE THREAD

**Issue by coolbeevip** [vipshop/vjtools#150]
com.sun.tools.attach.AttachNotSupportedException: Unable to open socket file: target process not responding or HotSpot VM not loaded
        at sun.tools.attach.LinuxVirtualMachine.<init>(LinuxVirtualMachine.java:106)
        at sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:63)
        at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:208)
        at com.vip.vjtools.vjtop.data.jmx.JmxClient.attachToGetConnectorAddress(JmxClient.java:225)
        at com.vip.vjtools.vjtop.data.jmx.JmxClient.connect(JmxClient.java:103)
        at com.vip.vjtools.vjtop.VMInfo.processNewVM(VMInfo.java:129)
        at com.vip.vjtools.vjtop.VJTop.main(VJTop.java:52)

**Comment by calvin1978** [comment]
需要在容器里执行，因为文件系统是隔离的，而java是通过socket file进去的
