### ISSUE TITLE
几个命令编译后都无法执行

### ISSUE THREAD

**Issue by xuminwlt** [vipshop/vjtools#43]
编译执行的，难道是我的使用方式或者环境不对吗？白衣大人

vjmap
[root@qa-admin vjmap]# ./vjmap.sh -all 5111
WARNING!! STW(Stop-The-World) will be performed on your Java process, if this is NOT wanted, type 'Ctrl+C' to exit.
sun.jvm.hotspot.runtime.VMVersionMismatchException: Supported versions are 25.111-b14. Target VM is 25.161-b14

[root@qa-admin vjmap]# java -version
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

vjtop
root@qa-admin vjtop]# ./vjtop.sh 5111
六月 20, 2018 5:43:49 下午 com.vip.vjtools.vjtop.VMInfo processNewVM
严重: could not attach (PID=5111)
java.io.IOException: Unable to open socket file: target process not responding or HotSpot VM not loaded
	at com.vip.vjtools.vjtop.data.jmx.JmxClient.getConnectorAddress(JmxClient.java:254)
	at com.vip.vjtools.vjtop.data.jmx.JmxClient.tryConnect(JmxClient.java:112)
	at com.vip.vjtools.vjtop.data.jmx.JmxClient.connect(JmxClient.java:102)
	at com.vip.vjtools.vjtop.VMInfo.processNewVM(VMInfo.java:132)
	at com.vip.vjtools.vjtop.VMDetailView.<init>(VMDetailView.java:44)
	at com.vip.vjtools.vjtop.VJTop.main(VJTop.java:88)
Caused by: com.sun.tools.attach.AttachNotSupportedException: Unable to open socket file: target process not responding or HotSpot VM not loaded
	at sun.tools.attach.LinuxVirtualMachine.<init>(LinuxVirtualMachine.java:106)
	at sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:63)
	at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:208)
	at com.vip.vjtools.vjtop.data.jmx.JmxClient.getConnectorAddress(JmxClient.java:252)
	... 5 more
ERROR: Could not attach to process.

**Comment by calvin1978** [comment]
你的目标应用JDK是用1.8.0_161在跑，而你执行vjmap的JDK是1.8.0_111

**Comment by xuminwlt** [comment]
发现问题了，的确是这个原因造成的，谢谢。

**Comment by calvin1978** [comment]
我也修改了一下README，强调了大家用同版本的JDK跑：）
